version: "3.4"

services:
  # PaperSpigot Server
  paper:
    build:
      context: ./DockerFiles/paper/
    volumes:
      - ./data/paper:/data
    ports:
      - 25565:25565

  # Auto job to backup server
  # This service must start up after PaperSpigot
  cron:
    build:
      context: ./DockerFiles/cron/
    volumes:
      - ./data/paper:/data
      - /var/run/docker.sock.raw:/var/run/docker.sock:ro
    depends_on:
      - paper
