version: "3.4"

services:
  paper:
    build:
      context: Dockerfiles/paper
      dockerfile: Dockerfile
    volumes:
      - ./data/paper:/data
  cron:
    build:
      context: Dockerfiles/cron
      dockerfile: Dockerfile
    volumes:
      - ./data/paper:/data