FROM azul/prime-debian
VOLUME ./paper /paper
RUN mv /etc/apt/sources.list /etc/apt/sources.list.old
RUN echo deb https://mirrors.tuna.tsinghua.edu.cn/debian/ bullseye main contrib non-free > /etc/apt/sources.list
RUN apt update
RUN apt install curl
RUN curl https://api.papermc.io/v2/projects/paper/versions/1.19.2/builds/131/downloads/paper-1.19.2-131.jar > /paper-1.19.2-131.jar
COPY ./launch_paper.sh /launch_paper.sh
RUN chmod 777 /launch_paper.sh
ENTRYPOINT [ "bash", "/launch_paper.sh" ]
