version: "3.4"

services:
  paper:
    build:
      context: ./Dockerfiles/paper
    volumes:
      - ./data/paper:/data
  cron:
    build:
      context: ./Dockerfiles/cron
    volumes:
      - ./data/paper:/data